# Generated by Django 2.0.2 on 2018-02-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='relaese_date',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
